In [1]:
import numpy as np
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

# Exercise

# Q1

In [3]:
# Re-run the sklearn block with k = 1, 3, 5, 7 in a loop and print each prediction. Where does it change?
df = pd.DataFrame({
    "Fruit": ["Apple", "Apple", "Apple",
              "Orange", "Orange", "Orange",
              "Banana", "Banana", "Banana"],
    "Weight": [150, 160, 140, 170, 165, 180, 120, 130, 115],
    "Size": [7, 7, 6, 9, 8, 9, 12, 13, 11],
    "Color": [200, 50, 220, 240, 250, 230, 30, 40, 20]
})

X = np.column_stack((df['Color'], df['Size'], df['Weight']))
y = df['Fruit'].values

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

model = KNeighborsClassifier(n_neighbors=3, weights='distance')
model.fit(X_scaled, y)

q = scaler.transform(np.array([[220, 8, 155]]))
print(model.classes_)
print(model.predict_proba(q))
print('Prediction:', model.predict(q)[0])

['Apple' 'Banana' 'Orange']
[[0.39084138 0.         0.60915862]]
Prediction: Orange

In [5]:
q = scaler.transform(np.array([[220, 8, 155]]))

for k in [1, 3, 5, 7]:
    model = KNeighborsClassifier(n_neighbors=k, weights='distance')
    model.fit(X_scaled, y)

    print(f'k={k}')
    print(model.classes_)
    print(model.predict_proba(q))
    print('prediction:', model.predict(q)[0])
    print('---')

k=1
['Apple' 'Banana' 'Orange']
[[1. 0. 0.]]
prediction: Apple
---
k=3
['Apple' 'Banana' 'Orange']
[[0.39084138 0.         0.60915862]]
prediction: Orange
---
k=5
['Apple' 'Banana' 'Orange']
[[0.4281896 0.        0.5718104]]
prediction: Orange
---
k=7
['Apple' 'Banana' 'Orange']
[[0.44586934 0.04173973 0.51239093]]
prediction: Orange
---

# Q2

In [9]:
X = np.column_stack((df['Color'], df['Size'], df['Weight']))
y = df['Fruit'].values

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

model = KNeighborsClassifier(n_neighbors=3, weights='distance')
model.fit(X_scaled, y)

q = scaler.transform(np.array([[220, 8, 155]]))
print(model.classes_)
print(model.predict_proba(q))
print('Prediction:', model.predict(q)[0])

['Apple' 'Banana' 'Orange']
[[0.39084138 0.         0.60915862]]
Prediction: Orange

In [10]:
X = np.column_stack((df['Color'], df['Size'], df['Weight']))
y = df['Fruit'].values

model = KNeighborsClassifier(n_neighbors=3, weights='distance')
model.fit(X, y)

q = scaler.transform(np.array([[220, 8, 155]]))
print(model.classes_)
print(model.predict_proba(q))
print('Prediction:', model.predict(q)[0])

['Apple' 'Banana' 'Orange']
[[0. 1. 0.]]
Prediction: Banana

**Answer:** *The X_scaled got all features consider, and the X raw got too much from feature who is higher number*

# Q3

In [12]:
# Swap weights='distance' for 'uniform' and compare predict_proba
X = np.column_stack((df['Color'], df['Size'], df['Weight']))
y = df['Fruit'].values

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

model = KNeighborsClassifier(n_neighbors=3, weights='uniform')
model.fit(X_scaled, y)

q = scaler.transform(np.array([[220, 8, 155]]))
print(model.classes_)
print(model.predict_proba(q))
print('Prediction:', model.predict(q)[0])

['Apple' 'Banana' 'Orange']
[[0.33333333 0.         0.66666667]]
Prediction: Orange

**Answer:** *uniform takes all the point weights as equall so the distance dont matter*

# learning

In [3]:
df = pd.DataFrame({
    "Fruit": ["Apple", "Apple", "Apple",
              "Orange", "Orange", "Orange",
              "Banana", "Banana", "Banana"],
    "Weight": [150, 160, 140, 170, 165, 180, 120, 130, 115],
    "Size": [7, 7, 6, 9, 8, 9, 12, 13, 11],
    "Color": [200, 50, 220, 240, 250, 230, 30, 40, 20]
})
df

    Fruit  Weight  Size  Color
0   Apple     150     7    200
1   Apple     160     7     50
2   Apple     140     6    220
3  Orange     170     9    240
4  Orange     165     8    250
5  Orange     180     9    230
6  Banana     120    12     30
7  Banana     130    13     40
8  Banana     115    11     20

In [7]:
wmax = df['Weight'].max()
wmin = df['Weight'].min()
print(wmax,wmin)

180 115

In [8]:
min_max_scaler = MinMaxScaler()

df_norm = df.copy()

######################### STEP 1 - normalize df
# 1 - each column separately
#df_norm['Weight'] = scaler.fit_transform(df['Weight'].values.reshape(-1, 1))
#df_norm['Size']   = scaler.fit_transform(df['Size'].values.reshape(-1, 1))
#df_norm['Color']  = scaler.fit_transform(df['Color'].values.reshape(-1, 1))

# 2 - all columns at once
# fit_transform - find min + max and scale
df_norm[['Weight', 'Color', 'Size']] = min_max_scaler.fit_transform(df_norm[['Weight', 'Color', 'Size']])

In [9]:
df_norm

    Fruit    Weight      Size     Color
0   Apple  0.538462  0.142857  0.782609
1   Apple  0.692308  0.142857  0.130435
2   Apple  0.384615  0.000000  0.869565
3  Orange  0.846154  0.428571  0.956522
4  Orange  0.769231  0.285714  1.000000
5  Orange  1.000000  0.428571  0.913043
6  Banana  0.076923  0.857143  0.043478
7  Banana  0.230769  1.000000  0.086957
8  Banana  0.000000  0.714286  0.000000

In [12]:
######################### STEP 2 - normalize the fruit with the same scaler
new_fruit = pd.DataFrame({'Weight': [155], 'Color': [220], 'Size': [8]})

# transform - scale only
new_fruit_norm = min_max_scaler.transform(new_fruit[['Weight', 'Color', 'Size']])
print('new_fruit_norm', new_fruit_norm)

new_fruit_norm [[0.61538462 0.86956522 0.28571429]]

In [15]:
######################### STEP 3 - find dist between the new_fruit and ALL other fruits
distances = []
for i in range(len(df_norm)):
    diff_arr = df_norm.iloc[i][['Weight', 'Color', 'Size']] - new_fruit_norm[0]
    dist = np.linalg.norm(diff_arr) # [1,2,3] = √[(1)² + (2)² + (3)²]
    distances.append( (i, dist, df_norm.iloc[i]['Fruit']) )

distances

[(0, np.float64(0.18408356716879312), 'Apple'),
 (1, np.float64(0.756729226771735), 'Apple'),
 (2, np.float64(0.3672697794960086), 'Apple'),
 (3, np.float64(0.2849983119390297), 'Orange'),
 (4, np.float64(0.20169747536206847), 'Orange'),
 (5, np.float64(0.4125863746131085), 'Orange'),
 (6, np.float64(1.139689036703703), 'Banana'),
 (7, np.float64(1.1272131325645076), 'Banana'),
 (8, np.float64(1.1482662415731868), 'Banana')]

In [17]:
######################### STEP 4 - sort by distance + choose first 5
d222 = sorted(distances, key=lambda item:item[1])[:5]

# d = [{'id': 1, 'dist': 3}, {'id': 2, 'dist': 2}]
# sorted(d, key=lambda item: item['dist'])

d222 # i did it myself

[(0, np.float64(0.18408356716879312), 'Apple'),
 (4, np.float64(0.20169747536206847), 'Orange'),
 (3, np.float64(0.2849983119390297), 'Orange'),
 (2, np.float64(0.3672697794960086), 'Apple'),
 (5, np.float64(0.4125863746131085), 'Orange')]

In [18]:
# just better looking

for i, d, label in sorted(distances, key=lambda item: item[1])[:5]:
    print(f'{label:7s} index={i}  d={d:.5f}')

Apple   index=0  d=0.18408
Orange  index=4  d=0.20170
Orange  index=3  d=0.28500
Apple   index=2  d=0.36727
Orange  index=5  d=0.41259

In [19]:

d221 = sorted(distances, key=lambda item:item[1])[:3]

d221 # k=3

[(0, np.float64(0.18408356716879312), 'Apple'),
 (4, np.float64(0.20169747536206847), 'Orange'),
 (3, np.float64(0.2849983119390297), 'Orange')]

# The codded KNN

In [35]:
# Fruit data
colors = np.array([200, 50, 220, 240, 250, 230, 30, 40, 20])
sizes = np.array([7, 7, 6, 9, 8, 9, 12, 13, 11])
weights = np.array([150, 160, 140, 170, 165, 180, 120, 130, 115])
fruit_types = np.array(['apple', 'apple', 'apple',
                        'orange', 'orange', 'orange',
                        'banana', 'banana', 'banana'])

# Create feature matrix
X = np.column_stack((colors, sizes, weights))
y = fruit_types

# Normalize data
scaler = MinMaxScaler() # create
X_scaled = scaler.fit_transform(X) # activate

k = 3   # number of neighbors
# weights = uniform  -- All points in each neighborhood are weighted equally
# weights = distance -- weight points by the inverse of their distance.
#                       closer neighbors of a query point will have a greater
#                       influence than neighbors which are further away.
model = KNeighborsClassifier(n_neighbors=k, weights='distance')

model.fit(X_scaled, y)  # store the points

KNeighborsClassifier(n_neighbors=3, weights='distance')

In [36]:
# New fruit to classify
new_fruit = np.array([[220, 8, 155]])
new_fruit_scaled = scaler.transform(new_fruit)

prediction = model.predict(new_fruit_scaled)
probabilities = model.predict_proba(new_fruit_scaled)
print(model.classes_)
print(probabilities)

# Output result
print(f"prediction: The new fruit is a {prediction[0]}")

['apple' 'banana' 'orange']
[[0.39084138 0.         0.60915862]]
prediction: The new fruit is a orange